
os: linux
language: node_js

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

node_js:
  - "8"

# skip fetching the git-lfs files
git:
  lfs_skip_smudge: true

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn

# no test task exist, yet, theirfore we test some other tasks (e.g. build)
script:
  - yarn test
  - yarn build:verbose
